# Generated by Django 5.2.7 on 2025-10-17 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "سبد خرید",
                "verbose_name_plural": "سبدهای خرید",
                "db_table": "carts",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=50, unique=True)),
                ("shipping_name", models.CharField(max_length=200)),
                ("shipping_address", models.TextField()),
                ("shipping_city", models.CharField(max_length=100)),
                ("shipping_state", models.CharField(max_length=100)),
                ("shipping_postal_code", models.CharField(max_length=20)),
                ("shipping_phone", models.CharField(max_length=15)),
                ("subtotal", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "shipping_cost",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                ("total", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پرداخت"),
                            ("processing", "در حال پردازش"),
                            ("shipped", "ارسال شده"),
                            ("delivered", "تحویل داده شده"),
                            ("cancelled", "لغو شده"),
                            ("refunded", "بازگشت وجه"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True, null=True)),
                ("is_paid", models.BooleanField(default=False)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارشات",
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=300)),
                ("product_sku", models.CharField(max_length=100)),
                ("unit_price", models.DecimalField(decimal_places=0, max_digits=12)),
                ("quantity", models.IntegerField(default=1)),
                ("subtotal", models.DecimalField(decimal_places=0, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم سفارش",
                "verbose_name_plural": "آیتم\u200cهای سفارش",
                "db_table": "order_items",
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="wishlists", to="products.product"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "لیست علاقه\u200cمندی",
                "verbose_name_plural": "لیست\u200cهای علاقه\u200cمندی",
                "db_table": "wishlists",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم سبد خرید",
                "verbose_name_plural": "آیتم\u200cهای سبد خرید",
                "db_table": "cart_items",
                "unique_together": {("cart", "product")},
            },
        ),
    ]
