# Generated by Django 5.2.7 on 2025-10-17 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExcelImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="excel_imports/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در حال پردازش"),
                            ("processing", "در حال پردازش"),
                            ("success", "موفق"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.IntegerField(default=0)),
                ("successful_imports", models.IntegerField(default=0)),
                ("failed_imports", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("error_details", models.JSONField(blank=True, default=dict)),
                (
                    "json_data",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="داده\u200cهای تبدیل شده به JSON",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ ورود اکسل",
                "verbose_name_plural": "لاگ\u200cهای ورود اکسل",
                "db_table": "excel_import_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImportError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.IntegerField()),
                ("sku", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("error_type", models.CharField(max_length=100)),
                ("error_message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="excel_import.excelimportlog",
                    ),
                ),
            ],
            options={
                "verbose_name": "خطای ورود محصول",
                "verbose_name_plural": "خطاهای ورود محصول",
                "db_table": "product_import_errors",
                "ordering": ["row_number"],
            },
        ),
    ]
