# Generated by Django

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_import', '0001_initial'),
    ]

    operations = [
        # اطمینان از اینکه فیلد uploaded_by null=False است
        migrations.AlterField(
            model_name='excelimportlog',
            name='uploaded_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                null=False,  # اجباری
            ),
        ),
    ]
