# Generated by Django 5.2.7 on 2025-10-17 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("zarinpal", "زرین\u200cپال"),
                            ("paypint", "پی\u200cپینگ"),
                            ("saman", "سامان"),
                            ("mellat", "ملت"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پرداخت"),
                            ("processing", "در حال پردازش"),
                            ("completed", "پرداخت موفق"),
                            ("failed", "پرداخت ناموفق"),
                            ("cancelled", "لغو شده"),
                            ("refunded", "بازگشت وجه"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        blank=True,
                        help_text="Authority from payment gateway",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference ID from gateway",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت",
                "verbose_name_plural": "پرداخت\u200cها",
                "db_table": "payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="request, verify, refund, etc.", max_length=50
                    ),
                ),
                ("request_data", models.JSONField(blank=True, default=dict)),
                ("response_data", models.JSONField(blank=True, default=dict)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("is_successful", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ پرداخت",
                "verbose_name_plural": "لاگ\u200cهای پرداخت",
                "db_table": "payment_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
